name: "Podcast Generator"
author: "Kalyan Kumar Guggulla"
description: "generates a feed for a podcost from a YAML file"
runs:
  using : "docker"
  image : "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: "The committer's email address"
    required: true
    default: "${{ github.actor }}@localhost"
  name:
    description: "The Commiter's name"
    required: true
    default: ${{ github.actor }}

